Feature/spielerkonto
HMSolution/YooLoo pull request #2
Opened 2020-01-22 08:37 UTC by chatn0ir07

Implementierung vom **Spielerkonto** Modul

> Spieler sollten vom Server über den Namen wiedererkannt werden (eindeutige
Identifikation) Die zuletzt gespielte Kartensortierung muss dann als
Ausgangslage für die neue Runde wiederhergestellt werden. Ein Spieler darf
nicht doppelt in einer Runde teilnehmen („Gegen sich selbst spielen“). 

Der Client liest beim Start den **Namen** und **IP/Hostname** aus `stdin` aus.
Beim Login speichert der Server die IP des Clients und dessen Socket in einer `LinkedHashMap<String, Socket>`, wenn der Client jetzt ein zweites mal gestartet wird, schließt der Server die Verbindung nachdem er ein `SERVERMESSAGE_ALREADY_LOGGED_IN` schickt

Die Kartenreihenfolge wird nach der Runde mit dem Benutzernamen gespeichert, und beim nächsten Login ausgelesen und als initiale Kartenreihenfolge zum Client geschickt .

Die beiden Schritte werden __nicht__ persistent gespeichert sondern sind nur zur Laufzeit im Arbeitsspeicher

2020-01-22 19:28 UTC, HMSolution requested changes
Bitte auf die Einrückung und Akzeptanztests achten!

2020-01-22 19:28 UTC, HMSolution commented on src/client/YoolooClient.java
> +				if(failedOnce) System.out.println("Dein Name muss mindestens 4 Zeichen lang sein.");
Change to nameNotLongEnough

2020-01-22 19:28 UTC, HMSolution commented on src/client/YoolooClient.java
> +			System.out.println("Logge als " + this.spielerName + " ein");
Maybe highlighting für "spielerName" ?
Und change to spielername (cause its one word not two, or am I wrong?)

2020-01-22 19:28 UTC, HMSolution commented on src/client/YoolooClient.java
> +					System.exit(0);
Bin ich jetzt dumm? Warum system.exit, dadurch killst du doch den Client oder nicht?

2020-01-22 19:28 UTC, HMSolution commented on src/client/YoolooClient.java
> +					System.out.println("Sende LoginMessage an Server");
"Login beim Server" oder "Du wirst eingeloggt"

2020-01-22 19:28 UTC, HMSolution commented on src/server/YoolooServer.java
> +	// private LinkedHashMap<Thread> spielerThreads;
Brauchst du das noch oder kann das weg?

2020-01-22 19:31 UTC, HMSolution requested changes
Change of indendation

2020-01-22 19:31 UTC, HMSolution commented on src/server/YoolooClientHandler.java
>  						for (int stichNummer = 0; stichNummer < YoolooKartenspiel.maxKartenWert; stichNummer++) {
Bitte auf die Einrückung achten

2020-01-22 19:35 UTC, chatn0ir07 commented on src/client/YoolooClient.java
> +					System.exit(0);
Ja, der Clientprozess wird beendet wenn er bereits eingeloggt ist, dabei wird aber nur 2. Prozess, also der doppelte beendet.

2020-01-23 09:13 UTC, soloblau approved these changes

2020-01-23 09:15 UTC, HMSolution approved these changes
Scheißcode

2020-01-23 09:16 UTC, merged