Feature/cheatkontrolle
HMSolution/YooLoo pull request #3
Opened 2020-01-22 11:02 UTC by HMSolution

Pls review with care tests are not created yet. Server and clients were adapted for receiving messages, to broadcast the cheat. The cheater himself is specifically told. Server is restarted when cheat occurs and all cheaters (also multiple) are expelled from the actual session.

2020-01-22 11:22 UTC, chatn0ir07 requested changes
Typ von `clientHandlerList` in `YoolooServer.java` muss geändert werden um nicht mit #2 in Konflikt zu geraten.

2020-01-22 11:22 UTC, chatn0ir07 commented on src/server/YoolooServer.java
> +		for(YoolooClientHandler handler : clientHandlerList)
Um zu vermeiden, dass sich Spieler doppelt anmelden können, habe ich in #2 hab ich den Typen von `clientHandlerList` auf `LinkedHashMap<String, YoolooClientHandler>` abgeändert.
Deshalb ist es nicht mehr möglich mittels einfachem schleifen-Konstrukt über die Liste zu iterieren, die `for` müsste so aussehen:
```java
for(Entry<String, YoolooClientHandler> ent : this.clientHandlerList.entrySet()) {
YoolooClientHandler handler = ent.getValue();
...
```

2020-01-22 11:22 UTC, chatn0ir07 commented on src/server/YoolooClientHandler.java
> +								System.out.println(ANSI_RED + "[ALERT] !!!!!Spielercheat erkannt!!!!! [ALERT]" + ANSI_RESET);
Wie bricht er hier ab?

2020-01-22 11:22 UTC, chatn0ir07 commented on src/server/YoolooServer.java
> +	   for(int i = 0; i < clientHandlerList.size(); i++)
Schleifenkonstrukt muss geändert werden um mit #2 kompatibel zu sein
```java
for(Entry<String, YoolooClientHandler> ent : this.clientHandlerList.entrySet()) {
Socket spielerSocket = ent.getValue().getSocket();
socketUtils.sendSerialized(spielerSocket, notificationForPlayerCheating);
}
```

2020-01-23 07:33 UTC, soloblau approved these changes

2020-01-23 07:43 UTC, chatn0ir07 approved these changes
Sieht gut aus

2020-01-23 15:20 UTC, merged